accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout')
]

attendance/urls.py
from django.urls import path
from . import views 

app_name = 'attendance'
urlpatterns = [
    path('', views.index, name='index'),
    #path('', views.result, name='result'),
    path('result/', views.result, name='result'),
]

clock/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('attendance.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    #path('',include('chat.urls'))
]

attendance/models.py
from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.
class SubmitAttendance(models.Model):

    class Meta:
        db_table = 'attendance'

    PLACES = (
        (1, 'GRC'),
        #(2, 'GRC 4F'),
    )
    IN_OUT = (
        (1, 'IN'),
        (0, 'OUT'),
    )

    staff = models.ForeignKey(get_user_model(), verbose_name="Member", on_delete=models.CASCADE, default=None)
    place = models.IntegerField(verbose_name='出勤場所名', choices=PLACES, default=None)

 

    in_out = models.IntegerField(verbose_name='IN/OUT', choices=IN_OUT, default=None)
    time = models.TimeField(verbose_name="打卡時間")
    date = models.DateField(verbose_name='打卡日')

chat/models.py
from django.db import models

# Create your models here.

attendance/forms.py
from django import forms
from .models import SubmitAttendance

class SubmitAttendanceForm(forms.ModelForm):

    class Meta:
        model = SubmitAttendance
        fields = ('place', 'in_out')

attendance/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import SubmitAttendance
from .forms import SubmitAttendanceForm
from datetime import datetime
from django.utils import timezone

# Create your views here.

class IndexView(LoginRequiredMixin, View):
    def get(self, request):
        form = SubmitAttendanceForm
        context = {
            'form': form,
            "user": request.user,
        }
        return render(request, 'attendance/index.html', context)
index = IndexView.as_view()

#...
class ResultView(View):
    def post(self, request):
        form = SubmitAttendanceForm(request.POST)
        now = datetime.now()
        month = now.month
        day = now.day
        hour = now.hour
        minute = now.minute

        obj = form.save(commit=False)
        obj.place = request.POST["place"]
        obj.in_out = request.POST["in_out"]
        obj.staff = request.user
        obj.date = datetime.now().date()
        obj.time = datetime.now().time()
        obj.save()
        if request.POST["in_out"] == '1':
            comment = str(month) + "月" + str(day) +"日" + str(hour) + "時" + str(minute) + "分\n" + "上班打卡確認！"
        else:
            comment = str(month) + "月" + str(day) +"日" + str(hour) + "時" + str(minute) + "分\n" + "下班打卡確認(^-^)！"
        context = {
            'place': SubmitAttendance.PLACES[int(obj.place)-1][1],
            'comment': comment,
        }
        return render(request, 'attendance/result.html', context)
result = ResultView.as_view()

def test(request):
    return render(request,'test.html')

chat/views.py
from django.shortcuts import render

# Create your views here.

attendance/templates/attendance/base.html
{% load static %}
<html>
<head>
    <meta charset='utf-8'>
    <link rel="stylesheet" type="text/css" href="{% static 'attendance/css/style.css' %}">
    打卡頁面
</head>    
<body>
    {% block content  %}
    {% endblock  %}
</body>
</html>

attendance/templates/attendance/index.html
{% extends "attendance/base.html" %}
{% block content %}

    {% if user.is_authenticated %}
        <div class="container">
            <form method="post" action="{% url 'attendance:result' %}">
            {% csrf_token %}
                <h1>{{  user  }}</h1>
                <h2 id="time"></h2>
                    <script>
                    time();
                    function time(){
                        var now = new Date();
                        document.getElementById("time").innerHTML = now.toLocaleString();
                    }
                    setInterval('time()',1000);
                    </script>
                <p>出勤場所：<input type="hidden" name="place">{{ form.place }}</p>
                <p>IN/OUT：<input type="hidden" name="in_out">{{ form.in_out }}</p>
                <table>
                    <caption>recond</caption>
                    <tr>
                      <th>NAME</th>
                      <th>ID</th>
                    </tr>
                    <tr>
                      <td>&nbsp;</td>
                      <td>&nbsp;</td>
                    </tr>
                    <tr>
                      <td>&nbsp;</td>
                      <td>&nbsp;</td>
                    </tr>
                    <tr>
                      <td>&nbsp;</td>
                      <td>&nbsp;</td>
                    </tr>
                </table>
                <head>
                    <meta charset="UTF-8">
                    <title>Websocket測試</title>
                    <link rel="stylesheet" href="/static/layui/css/layui.css" media="all">
                    <script src="http://cdn.bootcss.com/jquery/1.12.3/jquery.min.js"></script>
                    <script src="/static/layui/layui.js"></script>
              </head>
              <body style="margin: auto">
                <script>
                    if ("WebSocket" in window) {
                        // 開啟一個 web socket
                        var ws = new WebSocket( "ws://"+ window.location.host + "/ws/attendance");
                        console.log("ws:" + window.location.host + "/ws/attendance")
                        console.log('ws',ws)
                        ws.onopen = function () {
                            // Web Socket 已連線上，使用 send() 方法傳送資料
                            alert("連結成功")
                            ws.send("傳送訊息");
                            console.log('onopen')
                            {alert("資料傳送中...");}
                        };
                        ws.onmessage = function (evt) {
                            var received_msg = evt.data;
                            {alert("資料已接收...");}
                            console.log("資料:" + received_msg)
                        };
                        ws.onclose = function () {
                            // 關閉 websocket
                            alert("連結關閉，請重試")
                            console.log("連線已關閉...");
                        };
                    }
                    else {
                        // 瀏覽器不支援 WebSocket
                        alert("您的瀏覽器不支援 WebSocket!");
                    }
                </script>


 

                <p><input class="btn btn-primary" type="submit" value="Submit"></p>
            </form>
            <a href="../accounts/logout">logout</a>
        </div>
    {% endif %}
{% endblock  %}

attendance/templates/attendance/result.html
{% extends "attendance/base.html" %}
{% block content %}
    <p>出勤場所：{{ place }}</p>
    <p>{{ comment }}</p>
    <a href="../accounts/logout">logout</a>
{% endblock  %}

attendance/templates/attendance/test.html
{% extends "attendance/base.html" %}
{% block content %}
    <head>
        <meta charset="UTF-8">
        <title>Websocket測試</title>
        <link rel="stylesheet" href="/static/layui/css/layui.css" media="all">
        <script src="http://cdn.bootcss.com/jquery/1.12.3/jquery.min.js"></script>
        <script src="/static/layui/layui.js"></script>
    </head>
    <body style="margin: auto">
    <script>
        if ("WebSocket" in window) {
            // 開啟一個 web socket
            var ws = new WebSocket(+ window.location.host + "/ws/test_async");
            console.log("ws:" + window.location.host + "/ws/test_async")
            console.log('ws',ws)
            ws.onopen = function () {
                // Web Socket 已連線上，使用 send() 方法傳送資料
                alert("連結成功")
                ws.send("傳送訊息");
                console.log('onopen')
                {alert("資料傳送中...");}
            };
            ws.onmessage = function (evt) {
                var received_msg = evt.data;
                {alert("資料已接收...");}
                console.log("資料:" + received_msg)
            };
            ws.onclose = function () {
                // 關閉 websocket
                alert("連結關閉，請重試")
                console.log("連線已關閉...");
            };
        }
        else {
            // 瀏覽器不支援 WebSocket
            alert("您的瀏覽器不支援 WebSocket!");
        }
    </script>
{% endblock  %}